version: '3.7'

services:
  app-20:
    build:
      # 指定 build context
      context: .
      # 指定 `Dockerfile` 的文件路径
      dockerfile: ./Dockerfile
    ports:
      - 8888:80
    # volumes 用来定义 bind mounts
    volumes:
      - .:/app/foo
    # environment 用来定义环境变量
    environment:
      - ENV_FOO=foo
